name: instagram_clone
description: A Flutter Instagram Clone UI project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ICON IOS
  cupertino_icons: ^1.0.6

  # STATE MANAGEMENT (sau này dùng luôn)
  provider: ^6.1.2

  # CHỌN ẢNH (dùng cho post, story)
  image_picker: ^1.0.7

  # HIỂN THỊ ẢNH MẠNG (sau này dùng API/Firebase)
  cached_network_image: ^3.3.1

  # ICON ĐẸP HƠN
  flutter_svg: ^2.0.10+1

  # FONT (nếu muốn custom)
  google_fonts: ^6.2.1

  # FORMAT TIME (ví dụ: "2 giờ trước")
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.2.4
  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  # ASSETS (ảnh local)
  assets:
    - assets/images/
    - assets/icons/

  # FONT (optional - nếu bạn muốn custom font)
  fonts:
    - family: LobsterTwo
      fonts:
        - asset: assets/fonts/LobsterTwo-Italic.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf