// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Wy76t1QRI84rM-OKVp9hgbpuQoHkhv4',
    appId: '1:723765596431:web:4ea814a602a38127856e7a',
    messagingSenderId: '723765596431',
    projectId: 'instagramcloneapp-68963',
    authDomain: 'instagramcloneapp-68963.firebaseapp.com',
    storageBucket: 'instagramcloneapp-68963.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARxPJyiVE5zcNjp9WXJWu6mypV_SzzvB4',
    appId: '1:723765596431:android:b37d1b8525f0dbdb856e7a',
    messagingSenderId: '723765596431',
    projectId: 'instagramcloneapp-68963',
    storageBucket: 'instagramcloneapp-68963.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbpdTu2ZZVOevKLsLKdxrJAN_CnH3M6Ps',
    appId: '1:723765596431:ios:e3dfc3bd117ed95c856e7a',
    messagingSenderId: '723765596431',
    projectId: 'instagramcloneapp-68963',
    storageBucket: 'instagramcloneapp-68963.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbpdTu2ZZVOevKLsLKdxrJAN_CnH3M6Ps',
    appId: '1:723765596431:ios:e3dfc3bd117ed95c856e7a',
    messagingSenderId: '723765596431',
    projectId: 'instagramcloneapp-68963',
    storageBucket: 'instagramcloneapp-68963.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Wy76t1QRI84rM-OKVp9hgbpuQoHkhv4',
    appId: '1:723765596431:web:2624ec53ee524f8e856e7a',
    messagingSenderId: '723765596431',
    projectId: 'instagramcloneapp-68963',
    authDomain: 'instagramcloneapp-68963.firebaseapp.com',
    storageBucket: 'instagramcloneapp-68963.firebasestorage.app',
  );

}